export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const LOADING_SPINNER = 'LOADING_SPINNER';
export const GOTO_URL = 'GOTO_URL';
export const ACTIVE_PRODUCT = 'ACTIVE_PRODUCT';
export const FILTER_BY_LOWEST = 'FILTER_BY_LOWEST';
export const FILTER_BY_HIGHEST = 'FILTER_BY_HIGHEST';
export const FILTER_BY_RANDOM = 'FILTER_BY_RANDOM';
export const FETCH_LIST_FROM_STORAGE = 'FETCH_LIST_FROM_STORAGE';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

