export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const LOADING_SPINNER = 'LOADING_SPINNER';
export const GOTO_URL = 'GOTO_URL';
export const ACTIVE_PRODUCT = 'ACTIVE_PRODUCT';